{% set name = "knockknock" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85cb70c5e9c8e487979aed394c4033e6e4594d272840c62c6c0c586877575fcb

build:
  number: 0
  noarch: python
  entry_points:
    - knockknock = knockknock.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - keyring
    - matrix_client
    - python >=3.6
    - python-telegram-bot
    - requests
    - twilio
    - yagmail >=0.11.214

test:
  imports:
    - knockknock
  commands:
    - knockknock --help

about:
  home: http://github.com/huggingface/knockknock
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Be notified when your training is complete with only two additional lines of code

extra:
  recipe-maintainers:
    - setu4993
