{% set name = "knockknock" %}
{% set version = "0.1.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1b7274b52e58bf1b1e0a8731a1d3bc2f6af677c02ddc46048587fd9c16cd9465

build:
  number: 0
  noarch: python
  entry_points:
    - knockknock = knockknock.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - keyring
    - python >=3.6
    - python-telegram-bot
    - requests
    - twilio
    - yagmail >=0.11.214

test:
  imports:
    - knockknock
  commands:
    - knockknock --help

about:
  home: "http://github.com/huggingface/knockknock"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Be notified when your training is complete with only two additional lines of code"

extra:
  recipe-maintainers:
    - setu4993
